#! /bin/bash
# INSTALL JENKINS ON LINUX WITH REMOTE ACCESS AS A SERVICE

# SETUP WILDFLY CONFIGURATION ENVIRONMENT AND PARAMETERS
. ./env/setEnv.sh

#CHECK IF JENKINS INSTALLED AND RETURN IF INSTALLED
. ./utils/exitIfInstalled.sh $jenkinsHome

# DOWNLOAD AND INSTALL JENKINS 10
./installs/installJenkins.sh

# START JENKINS SERVICE
service jenkins start
